### PR TITLE
Merging Grahams CI Project Into Main

### PR DESCRIPTION
**Pull request by GrahamPaasch**
ci added
project restructured
swagger updated
MongoStore implemented

### CODE REVIEW

**Comment by GrahamPaasch** [comment]
Here is why ChatGPT recommended restructuring:

Structure 1:

Pros:
Simpler structure, easier to navigate for small projects.
Cons:
All files are at the root level or only one level deep, which can get cluttered as the project grows.
Missing package.json and package-lock.json which are important for Node.js projects.
No dedicated docs directory to store documentation.
Structure 2:

Pros:
More organized with a dedicated src (source) directory to store all the source code.
Docker files are organized in a docker directory.
Has a dedicated docs directory to store documentation.
Includes package.json and package-lock.json for Node.js dependency management.
Cons:
Slightly more complex due to additional directories, but this is necessary for better organization.
Recommendation:
Structure 2 is the better option because it is more organized and scalable for future growth. The additional directories (src, docker, docs) help to keep related files together, which makes the project easier to maintain. The inclusion of package.json and package-lock.json is also beneficial for Node.js projects. Overall, Structure 2 provides a solid foundation for a scalable and maintainable project.

**Comment by GrahamPaasch** [comment]
Also relevant to folder restructuring decisions is the Filesystem Hierarchy Standard by The Linux Foundation LSB Workgroup:
https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html

**Comment by FlatBallFlyer** [comment]
There is no need for npm in this project, ChatGPT was confused by the swagger document, which is just documentation. Please remove ```package.json``` and ```package-lock.json``` as this is not a node project. 

Please remove the ```synapse_COR.md``` from the root folder. 

I'm not sure I like the cd to a global find in the bash scripts, but I'm open to being convinced. On my Mac it takes it over 40 seconds to run, generates warnings about access to restricted folders, and ends up in the wrong folder - I have more than one folder with that name on my system. I usually write my scripts based on the assumption that they are being run in the context of the current folder. I guess that is also why I always execute scripts with ./ I suppose if you modified the find to look only from ../ and below, or ../../ and below it might come closer to working as expected?

**Comment by GrahamPaasch** [comment]
> DONE: There is no need for npm in this project, ChatGPT was confused by the swagger document, which is just documentation. Please remove `package.json` and `package-lock.json` as this is not a node project.
> 
> DONE: Please remove the `synapse_COR.md` from the root folder.
> 
> NOTE: I'm not sure I like the cd to a global find in the bash scripts, but I'm open to being convinced. On my Mac it takes it over 40 seconds to run, generates warnings about access to restricted folders, and ends up in the wrong folder - I have more than one folder with that name on my system. I usually write my scripts based on the assumption that they are being run in the context of the current folder. I guess that is also why I always execute scripts with ./ I suppose if you modified the find to look only from ../ and below, or ../../ and below it might come closer to working as expected? | NOTE: context of the current folder makes sense, I don't think I can make that command work consistently across operating systems unfortunately, so I'll change it

**Pull request merged**
